version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 654654531081.dkr.ecr.us-east-1.amazonaws.com/ocr-worker
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ocr-worker .
      - docker tag ocr-worker:latest 654654531081.dkr.ecr.us-east-1.amazonaws.com/ocr-worker:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 654654531081.dkr.ecr.us-east-1.amazonaws.com/ocr-worker:latest
artifacts:
  files: '**/*'

  
